config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "events#index"
  resources :bookings, only: [ :new, :create, :show, :destroy ]
  resources :events
  resources :users, only: [ :show ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :bookings, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :bookings

  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date > ?", Date.today).or(Event.where(date: nil)) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  has_many :bookings, foreign_key: :attendee_id
  has_many :attended_events, through: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @user = current_user
    @event = Event.find(params[:attended_event_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @event = Event.find(params[:booking][:attended_event_id].to_i)
    @booking = @user.bookings.build(attended_event: @event)
    if !already_attending? && @booking.save
      redirect_to user_path(@user)
    else
      if already_attending?
        flash.now[:alert] = "Already Attending"
      else
        flash.now[:alert] = "Error While Booking"
      end
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to user_path(current_user), notice: "You have successfully withdrawn from the event."
    else
      redirect_to user_path(current_user), alert: "Something went wrong."
    end
  end

  private

  def already_attending?
    @user = current_user
    event_id = (params[:booking][:attended_event_id].to_i)
    attending_events[event_id] > 1
  end

  def attending_events
    attending_events = {}
    @user.bookings.each do |booking|
      if attending_events[booking.attended_event_id].nil?
        attending_events[booking.attended_event_id] = 1
      else
        attending_events[booking.attended_event_id] += 1
      end
    end
    attending_events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login

  def index
    @user = current_user
    @events = Event.all
  end

  def new
    @user = current_user
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
    @event = Event.find(params[:id])
  end

  def edit
    @user = current_user
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = current_user
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_path(@user), status: :see_other
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :date, :location)
  end

  def require_login
    redirect_to new_user_session_path if !user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = current_user
    @events = @user.created_events
    redirect_to user_path(@user), alert: "Access denied" if @user.id != params[:id].to_i
  end

  private

  def require_login
    redirect_to new_user_session_path if !user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<h1>Bookings</h1>
<%= link_to 'My Events', user_path(@user)   %>
<br><br>
<%= form_with model: @booking do |form| %>
  <h3>Created By: <%= @event.creator.name %></h2>
  <br>
  <%= form.label "Event name: #{@event.name }" %>
  <br>
  <br>
  <%= form.label "Event Description: #{@event.description }" %>
  <br>
  <br>
  <%= form.label "Event Date: #{@event.date }" %>
  <br>
  <br>
  <%= form.label "Event Location: #{@event.location }" %>
  <br>
  <br>
  <%= form.hidden_field :attended_event_id, value: @event.id %>
  <%= form.hidden_field :attendee_id, value: current_user.id %>
  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit an Event</h1>
<%= link_to 'My Events', user_path(@user)   %>
<br><br>
<%= form_with model: @event do |form| %>
  <%= form.label "Event name" %>
  <%= form.text_field :name %>
  <br>
  <br>
  <%= form.label "Event Description" %>
  <%= form.text_area :description %>
  <br>
  <br>
  <%= form.label "Event Date" %>
  <%= form.date_field :date %>
  <br>
  <br>
  <%= form.label "Event Location" %>
  <%= form.text_field :location %>
  <br>
  <br>
  <%= form.submit %>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to 'My Events', user_path(@user)   %>
<br><br>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% if @events.any? %>
  <% @events.each do |event|%>
    <ul>
      <li>
        <h2><%= link_to event.name, event_path(event) %>  </h2>
        <%= link_to 'Attend Event', new_booking_path(attended_event_id: event.id, attendee_id: current_user.id) %>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>Create an Event</h1>
<%= link_to 'My Events', user_path(@user)   %>
<br><br>
<%= form_with model: @event do |form| %>
  <%= form.label "Event name" %>
  <%= form.text_field :name %>
  <br>
  <br>
  <%= form.label "Event Description" %>
  <%= form.text_area :description %>
  <br>
  <br>
  <%= form.label "Event Date" %>
  <%= form.date_field :date %>
  <br>
  <br>
  <%= form.label "Event Location" %>
  <%= form.text_field :location %>
  <br>
  <br>
  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<%= link_to 'All Events', events_path   %>
<br><br>
<%= link_to 'My Events', user_path(@user)   %>
<br><br>
<% if @event.creator.id == @user.id %>
  <%= link_to 'Edit event', edit_event_path(@event) %>
  <br><br>
  <%= link_to "Delete Event", event_path(@event), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
<% end %>
<br><br>
<% booking = @user.bookings.find_by(attended_event_id: @event.id) %>
<% if booking %>
  <%= link_to "Withdraw from Event", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>
<br><br>
<% if !@user.attended_events.include?(@event)%>
  <%= link_to 'Attend Event', new_booking_path(attended_event_id: @event.id, attendee_id: @user.id) %>
<% end %>
<br><br>
<h1><%= @event.name %></h1>
<p><%= @event.description %></p>
<h3>Date: <%= @event.date %></h3>
<h3>Location: <%= @event.location %></h3>

<h2>Attending</h2>
<% @event.attendees.each do |user| %>
  <ul>
    <li><%= user.name %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Created Events</h1>
<%= link_to 'All Events', events_path   %>
<br><br>
<%= link_to 'Create Event', new_event_path %>
<br><br>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<br>
<% @events.each do |event|%>
  <ul>
    <li><%= link_to event.name , event_path(event) %></li>
  </ul>
<% end %>

<br>
<h1>Attending Events</h1>

<h2>Past Events</h2>
<ul>
  <% Event.past.each do |event|%>
    <% if @user.attended_events.include?(event) %>
      <li><%= link_to event.name, event_path(event) %></li>
    <% end%>
  <% end %>
</ul>
<h2>Upcoming Events</h2>
<ul>
  <% Event.upcoming.each do |event|%>
    <% if @user.attended_events.include?(event) %>
      <li><%= link_to event.name, event_path(event) %></li>
    <% end %>
  <% end %>
</ul>